% Path to font files
\def\Fontbase{C:/Windows/Fonts}

% Font: Main font, \textnormal{}, \normalfont.
\setmainfont
[Path=\Fontbase/Times New Roman/,
ItalicFont=Times New Roman Italic,
BoldFont=Times New Roman Bold,
BoldItalicFont=Times New Roman Bold Italic,
Scale=1.00]
{Times New Roman Regular.ttf}

% Font: Roman font, \textrm{}, \rmfamily.
\setromanfont
[Path=\Fontbase/Times New Roman/,
ItalicFont=Times New Roman Italic,
BoldFont=Times New Roman Bold,
BoldItalicFont=Times New Roman Bold Italic,
Scale=1.00]
{Times New Roman Regular.ttf}

% Font: Sans-serif font, \textsf{}, \sffamily.
\setsansfont
[Path=\Fontbase/Arial/,
ItalicFont=Arial Italic,
BoldFont=Arial Bold,
BoldItalicFont=Arial Bold Italic,
Scale=1.00]
{Arial Regular.ttf}

% Font: Monospace font, \texttt{}, \ttfamily.
\setmonofont
[Path=\Fontbase/Courier New/,
ItalicFont=Courier New Italic,
BoldFont=Courier New Bold,
BoldItalicFont=Courier New Bold Italic,
Scale=0.95]
{Courier New Regular.ttf}
